+++ bs_bot.l
++++ en_us: lamego
++++ nl : ^Stinger^

+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_SUMMARY(en_us)
Dislays information about a bot.
+BS_INFO_SUMMARY(nl)
Geeft informatie weer over een bot
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_SYNTAX(en_us)
 // INFO bot_nick
+BS_INFO_SYNTAX(pt)
 // DROP nick_do_bot
+BS_INFO_SYNTAX(nl)
 // INFO bot_bijnaam
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_HELP(en_us)
Displays information about a bot.
@BS_INFO_SYNTAX
+BS_INFO_HELP(nl)
Geeft informatie weer over een bot
@BS_INFO_SYNTAX
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_SYNTAX_INV(en_us)
Invalid syntax !

@BS_INFO_SYNTAX
+BS_INFO_SYNTAX_INV(nl)
Ongeldige syntax !

@BS_INFO_SYNTAX
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_BOT_X_NOT_FOUND(en_us)
There is no such bot \B%s\B !
+BS_INFO_BOT_X_NOT_FOUND(pt)
O bot \B%s\B não existe !
+BS_INFO_BOT_X_NOT_FOUND(nl)
Er is geen bot \B%s\B !
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_HEADER(en_us)
######## Bot Info ########
+BS_INFO_HEADER(nl)
######## Bot Info ########
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_NICK(en_us)
Nick........: %s
+BS_INFO_NICK(nl)
Bijnaam........: %s
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_MASK(en_us)
Mask........: %s
+BS_INFO_MASK(nl)
Masker.........: %s
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_REALNAME(en_us)
Realname....: %s
+BS_INFO_REALNAME(nl)
Echte naam.....: %s 
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_OWNER(en_us)
Owner.......: %s
+BS_INFO_OWNER(nl)
Eigenaar.......: %s
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_CREATED(en_us)
Created.....: %s
+BS_INFO_CREATED(nl)
Aangemaakt.....: %s
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_EXPIRES(en_us)
Expires.....: %s
+BS_INFO_EXPIRES(nl)
Verloopt op....: %s
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_ASSIGNED_TO_X(en_us)
Assigned to.: %s
+BS_INFO_ASSIGNED_TO_X(nl)
Toegewezen aan.: %s
+++++++++++++++++++++++++++++++++++++++++++++
+BS_INFO_TAIL(en_us)
##########################
+BS_INFO_TAIL(nl)
##########################
+++++++++++++++++++++++++++++++++++++++++++++