++++ memoserv.l
++++ en_us: Lamego, Stinger
++++ nl: Stinger
++++ pt_br: openglx
++++ de: jo

+YOU_HAVE_X_UNREAD_MEMOS(en_us)
You have \B%d\B unread memo(s).
+YOU_HAVE_X_UNREAD_MEMOS(pt)
Tem \B%d\B memo(s) por ler.
+YOU_HAVE_X_UNREAD_MEMOS(nl)
U heeft \B%d\B ongelezen memo(s).
+YOU_HAVE_X_UNREAD_MEMOS(pt_br)
Você tem \B%d\B memo(s) não lido(s).
+YOU_HAVE_X_UNREAD_MEMOS(de)
Du hast \B%d\B ungelesen Memo(s).
