# $Id: bs_chan.sql,v 1.2 2005/10/04 16:31:48 jpinto Exp $
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS bs_chan;
CREATE TABLE bs_chan(
  scid INT UNSIGNED NOT NULL,
  bid INT UNSIGNED NOT NUL,
  PRIMARY KEY (bid, scid),
  CONSTRAINT FK_BSC1 FOREYGN KEY (bid) REFERENCES botserv(bid) 
	ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_BSC1 FOREYGN KEY (scid) REFERENCES chanserv(scid)
	ON DELETE CASCADE ON UPDATE CASCADE
) Type = InnoDB;

SET FOREIGN_KEY_CHECKS = 1;
